version: '2.29.7'

services:
  postgres:
    container_name: nest-clean-pg
    image: bitnami/postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: curso_bd
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres